name: Scan with ClamAV

on: [push, pull_request]

jobs:
  scan_with_clamav:
    runs-on: ubuntu-latest
    steps:
      - name: Vérifier le repo (checkout)
        uses: actions/checkout@v4

      - name: Installer ClamAV
        run: sudo apt-get update && sudo apt-get install -y clamav clamav-daemon

      - name: Arrêter le service freshclam (si en cours d’exécution)
        run: sudo systemctl stop clamav-freshclam || true

      - name: Mettre à jour la base de signatures
        run: sudo freshclam --stdout

      - name: Démarrer le service freshclam (si en cours d’exécution)
        run: sudo systemctl start clamav-freshclam || true

      - name: Scanner tous les fichiers .exe avec ClamAV
        id: scan
        continue-on-error: true
        run: |
          touch infected_files.txt
          set +e  # Désactive l'arrêt automatique en cas d'erreur
          
          find . -type f -name "*.exe" | while read file; do
            scan_result=$(clamscan --infected "$file")
            if echo "$scan_result" | grep -q "FOUND"; then
              echo "❌ Fichier infecté détecté: $file"
              echo "$file" >> infected_files.txt
              clamscan --remove "$file"  # Supprime après enregistrement
            fi
          done

      - name: Vérifier si un malware a été détecté
        run: |
          if [ -s infected_files.txt ]; then
            echo "🚨 Malware détecté dans les fichiers suivants :"
            cat infected_files.txt
            exit 1  # Échoue le job si un malware est détecté
          else
            echo "✅ Aucun malware détecté."
          fi

      - name: Sauvegarder la liste des fichiers infectés en tant qu’artefact
        uses: actions/upload-artifact@v4
        if: always()  # Toujours sauvegarder l'artefact, même si le job échoue
        with:
          name: fichiers-infectés
          path: infected_files.txt
