name: Scan with ClamAV

on: [push, pull_request]

jobs:
  scan_with_clamav:
    runs-on: ubuntu-latest
    steps:
      - name: Vérifier le repo (checkout)
        uses: actions/checkout@v4

      - name: Installer ClamAV
        run: sudo apt-get update && sudo apt-get install -y clamav clamav-daemon

      - name: Arrêter le service freshclam (si en cours d’exécution)
        run: sudo systemctl stop clamav-freshclam || true

      - name: Mettre à jour la base de signatures
        run: sudo freshclam --stdout

      - name: Démarrer le service freshclam (si en cours d’exécution)
        run: sudo systemctl start clamav-freshclam || true

      - name: Scanner tous les fichiers .exe avec ClamAV
        id: scan
        continue-on-error: true
        run: |
          touch infected_files.txt
          find . -type f -name "*.exe" | while read file; do
            clamscan --infected --remove "$file"
            scan_exit_code=$?  # Capture le code de sortie de clamscan
            
            if [ $scan_exit_code -eq 1 ]; then
              echo "❌ Fichier infecté détecté: $file"
              echo "$file" >> infected_files.txt
            fi
          done

      - name: Vérifier si un malware a été détecté
        run: |
          if [ -s infected_files.txt ]; then
            echo "🚨 Malware détecté dans les fichiers suivants :"
            cat infected_files.txt
            exit 1  # Échoue le job si au moins un fichier est infecté
          else
            echo "✅ Aucun malware détecté."
          fi
